### ISSUE TITLE
NameError when using GR backend in matplotlib

### ISSUE THREAD

**Issue by Juanlu001** [jheinen/gr#21]
python 3.5, matplotlib 1.5.0, example from https://github.com/jheinen/gr/blob/3f22b5d/examples/matplotlib/rotate_axes3d_demo.py:

```bash
$ MPLBACKEND="module://gr.matplotlib.backend_gr" python rotate_axes3d_demo.py 
Traceback (most recent call last):
  File "rotate_axes3d_demo.py", line 8, in <module>
    ax = fig.add_subplot(111, projection='3d')
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/figure.py", line 1005, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 125, in __init__
    self.figure.add_axes(self)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/figure.py", line 920, in add_axes
    self.stale = True
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/artist.py", line 267, in stale
    self.stale_callback(self, val)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 568, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2026, in draw_idle
    self.draw(*args, **kwargs)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/gr/matplotlib/backend_gr.py", line 235, in draw
    self.figure.draw(self.renderer)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/figure.py", line 1133, in draw
    func(*args)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 287, in draw
    ax.draw_pane(renderer)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/mpl_toolkits/mplot3d/axis3d.py", line 204, in draw_pane
    self.pane.draw(renderer)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/matplotlib/patches.py", line 522, in draw
    renderer.draw_path(gc, tpath, affine, rgbFace)
  File "/home/juanlu/.miniconda3/envs/poliastro35/lib/python3.5/site-packages/gr/matplotlib/backend_gr.py", line 81, in draw_path
    if type(gc._linestyle) is unicode:
NameError: name 'unicode' is not defined
```

**Comment by jheinen** [comment]
This problem is solved with commit 7b5eec4 (Improved Python 3 compatibility)
